[package]
name = "crystal_bin"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
crystal = { version = "0.1.0", path = "../crystal" }
winit = "0.30.8"
wgpu = "24.0.1"
pollster = "0.2.4"


[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3