[package]
name = "crystal_bin"
version = "0.1.0"
edition = "2021"

[dependencies]
crystal = { version = "0.1.0", path = "../crystal" }
winit = "0.30.8"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3