[package]
name = "crystal_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
crystal = { version = "0.1.0", path = "../crystal" }
egui = "0.30.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3