[package]
name = "crystal"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
winit = "0.30.8"
pollster = "0.2.4"
wgpu = "24.0.1"
rapier2d = "0.23.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3